(define (domain satellite)
    (:requirements :derived-predicates :existential-preconditions :negative-preconditions :strips :typing)
    (:types direction instrument mode satellite)
    (:predicates (calibrate_ ?s - satellite ?i - instrument ?d - direction)  (calibrated ?i - instrument)  (calibrated_AG ?i - instrument)  (calibrated_G ?i - instrument)  (calibrated_UG ?i - instrument)  (calibration_target ?i - instrument ?d - direction)  (calibration_target_AG ?i - instrument ?d - direction)  (calibration_target_G ?i - instrument ?d - direction)  (calibration_target_UG ?i - instrument ?d - direction)  (derivable_calibrate) (derivable_have_image_UG) (derivable_switch_off) (derivable_switch_on) (derivable_take_image) (derivable_turn_to) (have_image ?d - direction ?m - mode)  (have_image_AG ?d - direction ?m - mode)  (have_image_G ?d - direction ?m - mode)  (have_image_UG ?d - direction ?m - mode)  (ins_config ?S ?I ?M ?D)  (on_board ?i - instrument ?s - satellite)  (on_board_AG ?i - instrument ?s - satellite)  (on_board_G ?i - instrument ?s - satellite)  (on_board_UG ?i - instrument ?s - satellite)  (pointing ?s - satellite ?d - direction)  (pointing_AG ?s - satellite ?d - direction)  (pointing_G ?s - satellite ?d - direction)  (pointing_UG ?s - satellite ?d - direction)  (power_avail ?s - satellite)  (power_avail_AG ?s - satellite)  (power_avail_G ?s - satellite)  (power_avail_UG ?s - satellite)  (power_on ?i - instrument)  (power_on_AG ?i - instrument)  (power_on_G ?i - instrument)  (power_on_UG ?i - instrument)  (supports ?i - instrument ?m - mode)  (supports_AG ?i - instrument ?m - mode)  (supports_G ?i - instrument ?m - mode)  (supports_UG ?i - instrument ?m - mode)  (switch_on_ ?i - instrument ?s - satellite)  (take_image_ ?s - satellite ?d - direction ?i - instrument ?m - mode)  (turn_to_ ?s - satellite ?d_new - direction ?d_prev - direction))
    (:derived (calibrate_ ?S ?I ?D) (exists (?M ?Dg) (and (ins_config ?S ?I ?M ?Dg) (not (calibrated ?I)))))
     (:derived (calibrated_AG ?i) (and (calibrated ?i) (calibrated_G ?i)))
     (:derived (calibrated_UG ?i) (and (not (calibrated ?i)) (calibrated_G ?i)))
     (:derived (calibration_target_AG ?i ?d) (and (calibration_target ?i ?d) (calibration_target_G ?i ?d)))
     (:derived (calibration_target_UG ?i ?d) (and (not (calibration_target ?i ?d)) (calibration_target_G ?i ?d)))
     (:derived (derivable_calibrate) (exists (?i - instrument ?d - direction ?s - satellite) (and (on_board ?i ?s) (calibration_target ?i ?d) (pointing ?s ?d) (power_on ?i) (calibrate_ ?s ?i ?d))))
     (:derived (derivable_have_image_UG) (exists (?M ?D) (have_image_UG ?D ?M)))
     (:derived (derivable_switch_off) (exists (?i - instrument ?s - satellite) (and (on_board ?i ?s) (power_on ?i))))
     (:derived (derivable_switch_on) (exists (?i - instrument ?s - satellite) (and (on_board ?i ?s) (power_avail ?s) (switch_on_ ?i ?s))))
     (:derived (derivable_take_image) (exists (?i - instrument ?d - direction ?m - mode ?s - satellite) (and (calibrated ?i) (on_board ?i ?s) (supports ?i ?m) (power_on ?i) (pointing ?s ?d) (take_image_ ?s ?d ?i ?m))))
     (:derived (derivable_turn_to) (exists (?d_new - direction ?d_prev - direction ?s - satellite) (and (pointing ?s ?d_prev) (not (pointing ?s ?d_new)) (turn_to_ ?s ?d_new ?d_prev))))
     (:derived (have_image_AG ?d ?m) (and (have_image ?d ?m) (have_image_G ?d ?m)))
     (:derived (have_image_UG ?d ?m) (and (not (have_image ?d ?m)) (have_image_G ?d ?m)))
     (:derived (ins_config ?S ?I ?M ?D) (and (have_image_UG ?D ?M) (supports ?I ?M) (on_board ?I ?S)))
     (:derived (on_board_AG ?i ?s) (and (on_board ?i ?s) (on_board_G ?i ?s)))
     (:derived (on_board_UG ?i ?s) (and (not (on_board ?i ?s)) (on_board_G ?i ?s)))
     (:derived (pointing_AG ?s ?d) (and (pointing ?s ?d) (pointing_G ?s ?d)))
     (:derived (pointing_UG ?s ?d) (and (not (pointing ?s ?d)) (pointing_G ?s ?d)))
     (:derived (power_avail_AG ?s) (and (power_avail ?s) (power_avail_G ?s)))
     (:derived (power_avail_UG ?s) (and (not (power_avail ?s)) (power_avail_G ?s)))
     (:derived (power_on_AG ?i) (and (power_on ?i) (power_on_G ?i)))
     (:derived (power_on_UG ?i) (and (not (power_on ?i)) (power_on_G ?i)))
     (:derived (supports_AG ?i ?m) (and (supports ?i ?m) (supports_G ?i ?m)))
     (:derived (supports_UG ?i ?m) (and (not (supports ?i ?m)) (supports_G ?i ?m)))
     (:derived (switch_on_ ?I ?S) (exists (?M ?Dg) (ins_config ?S ?I ?M ?Dg)))
     (:derived (take_image_ ?S ?D ?I ?M) (ins_config ?S ?I ?M ?D))
     (:derived (turn_to_ ?S ?Dn ?Dp) (and (not (derivable_have_image_UG)) (pointing_UG ?S ?Dn)))
     (:derived (turn_to_ ?S ?Dn ?Dp) (exists (?I ?M ?Dg) (and (ins_config ?S ?I ?M ?Dg) (calibration_target ?I ?Dn) (power_on ?I) (not (calibrated ?I)) (not (derivable_calibrate)) (not (derivable_take_image)))))
     (:derived (turn_to_ ?S ?Dn ?Dp) (exists (?M ?I) (and (ins_config ?S ?I ?M ?Dn) (calibrated ?I) (not (derivable_calibrate)) (not (derivable_take_image)))))
    (:action calibrate
        :parameters (?s - satellite ?i - instrument ?d - direction)
        :precondition (and (on_board ?i ?s) (calibration_target ?i ?d) (pointing ?s ?d) (power_on ?i) (calibrate_ ?s ?i ?d))
        :effect (calibrated ?i)
    )
     (:action switch_off
        :parameters (?i - instrument ?s - satellite)
        :precondition (and (on_board ?i ?s) (power_on ?i))
        :effect (and (not (power_on ?i)) (power_avail ?s))
    )
     (:action switch_on
        :parameters (?i - instrument ?s - satellite)
        :precondition (and (on_board ?i ?s) (power_avail ?s) (switch_on_ ?i ?s))
        :effect (and (power_on ?i) (not (calibrated ?i)) (not (power_avail ?s)))
    )
     (:action take_image
        :parameters (?s - satellite ?d - direction ?i - instrument ?m - mode)
        :precondition (and (calibrated ?i) (on_board ?i ?s) (supports ?i ?m) (power_on ?i) (pointing ?s ?d) (take_image_ ?s ?d ?i ?m))
        :effect (have_image ?d ?m)
    )
     (:action turn_to
        :parameters (?s - satellite ?d_new - direction ?d_prev - direction)
        :precondition (and (pointing ?s ?d_prev) (not (pointing ?s ?d_new)) (turn_to_ ?s ?d_new ?d_prev))
        :effect (and (pointing ?s ?d_new) (not (pointing ?s ?d_prev)))
    )
)