(define (domain rover)
    (:requirements :derived-predicates :existential-preconditions :negative-preconditions :strips :typing)
    (:types camera lander mode objective rover store waypoint)
    (:predicates (at ?x - rover ?y - waypoint)  (at_AG ?x - rover ?y - waypoint)  (at_G ?x - rover ?y - waypoint)  (at_UG ?x - rover ?y - waypoint)  (at_lander ?x - lander ?y - waypoint)  (at_lander_AG ?x - lander ?y - waypoint)  (at_lander_G ?x - lander ?y - waypoint)  (at_lander_UG ?x - lander ?y - waypoint)  (at_rock_sample ?w - waypoint)  (at_rock_sample_AG ?w - waypoint)  (at_rock_sample_G ?w - waypoint)  (at_rock_sample_UG ?w - waypoint)  (at_soil_sample ?w - waypoint)  (at_soil_sample_AG ?w - waypoint)  (at_soil_sample_G ?w - waypoint)  (at_soil_sample_UG ?w - waypoint)  (calibrate_ ?r - rover ?i - camera ?t - objective ?w - waypoint)  (calibrated ?c - camera ?r - rover)  (calibrated_AG ?c - camera ?r - rover)  (calibrated_G ?c - camera ?r - rover)  (calibrated_UG ?c - camera ?r - rover)  (calibration_target ?i - camera ?o - objective)  (calibration_target_AG ?i - camera ?o - objective)  (calibration_target_G ?i - camera ?o - objective)  (calibration_target_UG ?i - camera ?o - objective)  (collected_image ?O ?M)  (collected_rock ?P)  (collected_soil ?P)  (communicate_image_data_ ?r - rover ?l - lander ?o - objective ?m - mode ?x - waypoint ?y - waypoint)  (communicate_rock_data_ ?r - rover ?l - lander ?p - waypoint ?x - waypoint ?y - waypoint)  (communicate_soil_data_ ?r - rover ?l - lander ?p - waypoint ?x - waypoint ?y - waypoint)  (communicated_image_data ?o - objective ?m - mode)  (communicated_image_data_AG ?o - objective ?m - mode)  (communicated_image_data_G ?o - objective ?m - mode)  (communicated_image_data_UG ?o - objective ?m - mode)  (communicated_rock_data ?w - waypoint)  (communicated_rock_data_AG ?w - waypoint)  (communicated_rock_data_G ?w - waypoint)  (communicated_rock_data_UG ?w - waypoint)  (communicated_soil_data ?w - waypoint)  (communicated_soil_data_AG ?w - waypoint)  (communicated_soil_data_G ?w - waypoint)  (communicated_soil_data_UG ?w - waypoint)  (derivable_calibrate) (derivable_calibrated_and_supports_mode ?M)  (derivable_communicate_image_data) (derivable_communicate_rock_data) (derivable_communicate_soil_data) (derivable_drop) (derivable_empty_rock) (derivable_empty_soil) (derivable_navigate) (derivable_sample_rock) (derivable_sample_soil) (derivable_take_image) (derivable_uncollected_goal_image) (derivable_uncollected_goal_rock) (derivable_uncollected_goal_soil) (empty ?s - store)  (empty_AG ?s - store)  (empty_G ?s - store)  (empty_UG ?s - store)  (equipped_for_imaging ?r - rover)  (equipped_for_imaging_AG ?r - rover)  (equipped_for_imaging_G ?r - rover)  (equipped_for_imaging_UG ?r - rover)  (equipped_for_rock_analysis ?r - rover)  (equipped_for_rock_analysis_AG ?r - rover)  (equipped_for_rock_analysis_G ?r - rover)  (equipped_for_rock_analysis_UG ?r - rover)  (equipped_for_soil_analysis ?r - rover)  (equipped_for_soil_analysis_AG ?r - rover)  (equipped_for_soil_analysis_G ?r - rover)  (equipped_for_soil_analysis_UG ?r - rover)  (full ?s - store)  (full_AG ?s - store)  (full_G ?s - store)  (full_UG ?s - store)  (have_image ?r - rover ?o - objective ?m - mode)  (have_image_AG ?r - rover ?o - objective ?m - mode)  (have_image_G ?r - rover ?o - objective ?m - mode)  (have_image_UG ?r - rover ?o - objective ?m - mode)  (have_rock_analysis ?r - rover ?w - waypoint)  (have_rock_analysis_AG ?r - rover ?w - waypoint)  (have_rock_analysis_G ?r - rover ?w - waypoint)  (have_rock_analysis_UG ?r - rover ?w - waypoint)  (have_soil_analysis ?r - rover ?w - waypoint)  (have_soil_analysis_AG ?r - rover ?w - waypoint)  (have_soil_analysis_G ?r - rover ?w - waypoint)  (have_soil_analysis_UG ?r - rover ?w - waypoint)  (navigate_ ?r - rover ?x - waypoint ?y - waypoint)  (navigate_priority) (on_board ?i - camera ?r - rover)  (on_board_AG ?i - camera ?r - rover)  (on_board_G ?i - camera ?r - rover)  (on_board_UG ?i - camera ?r - rover)  (sample_rock_ ?x - rover ?s - store ?p - waypoint)  (sample_soil_ ?x - rover ?s - store ?p - waypoint)  (store_of ?s - store ?r - rover)  (store_of_AG ?s - store ?r - rover)  (store_of_G ?s - store ?r - rover)  (store_of_UG ?s - store ?r - rover)  (supports ?c - camera ?m - mode)  (supports_AG ?c - camera ?m - mode)  (supports_G ?c - camera ?m - mode)  (supports_UG ?c - camera ?m - mode)  (supports_mode ?R ?I ?M)  (take_image_ ?r - rover ?p - waypoint ?o - objective ?i - camera ?m - mode)  (uncollected_goal_image ?O ?M)  (uncollected_goal_rock ?P)  (uncollected_goal_soil ?P)  (visible ?w - waypoint ?p - waypoint)  (visible_AG ?w - waypoint ?p - waypoint)  (visible_G ?w - waypoint ?p - waypoint)  (visible_UG ?w - waypoint ?p - waypoint)  (visible_from ?o - objective ?w - waypoint)  (visible_from_AG ?o - objective ?w - waypoint)  (visible_from_G ?o - objective ?w - waypoint)  (visible_from_UG ?o - objective ?w - waypoint))
    (:derived (at_AG ?x - rover ?y - waypoint) (and (at ?x ?y) (at_G ?x ?y)))
     (:derived (at_UG ?x - rover ?y - waypoint) (and (not (at ?x ?y)) (at_G ?x ?y)))
     (:derived (at_lander_AG ?x - lander ?y - waypoint) (and (at_lander ?x ?y) (at_lander_G ?x ?y)))
     (:derived (at_lander_UG ?x - lander ?y - waypoint) (and (not (at_lander ?x ?y)) (at_lander_G ?x ?y)))
     (:derived (at_rock_sample_AG ?w - waypoint) (and (at_rock_sample ?w) (at_rock_sample_G ?w)))
     (:derived (at_rock_sample_UG ?w - waypoint) (and (not (at_rock_sample ?w)) (at_rock_sample_G ?w)))
     (:derived (at_soil_sample_AG ?w - waypoint) (and (at_soil_sample ?w) (at_soil_sample_G ?w)))
     (:derived (at_soil_sample_UG ?w - waypoint) (and (not (at_soil_sample ?w)) (at_soil_sample_G ?w)))
     (:derived (calibrate_ ?R - rover ?I - camera ?T - objective ?W - waypoint) (exists (?O ?M) (and (supports_mode ?R ?I ?M) (uncollected_goal_image ?O ?M) (not (calibrated ?I ?R)))))
     (:derived (calibrated_AG ?c - camera ?r - rover) (and (calibrated ?c ?r) (calibrated_G ?c ?r)))
     (:derived (calibrated_UG ?c - camera ?r - rover) (and (not (calibrated ?c ?r)) (calibrated_G ?c ?r)))
     (:derived (calibration_target_AG ?i - camera ?o - objective) (and (calibration_target ?i ?o) (calibration_target_G ?i ?o)))
     (:derived (calibration_target_UG ?i - camera ?o - objective) (and (not (calibration_target ?i ?o)) (calibration_target_G ?i ?o)))
     (:derived (collected_image ?O ?M) (exists (?R) (have_image ?R ?O ?M)))
     (:derived (collected_rock ?P) (exists (?R) (have_rock_analysis ?R ?P)))
     (:derived (collected_soil ?P) (exists (?R) (have_soil_analysis ?R ?P)))
     (:derived (communicate_image_data_ ?R - rover ?L - lander ?O - objective ?M - mode ?X - waypoint ?Y - waypoint) (communicated_image_data_UG ?O ?M))
     (:derived (communicate_rock_data_ ?R - rover ?L - lander ?P - waypoint ?X - waypoint ?Y - waypoint) (communicated_rock_data_UG ?P))
     (:derived (communicate_soil_data_ ?R - rover ?L - lander ?P - waypoint ?X - waypoint ?Y - waypoint) (communicated_soil_data_UG ?P))
     (:derived (communicated_image_data_AG ?o - objective ?m - mode) (and (communicated_image_data ?o ?m) (communicated_image_data_G ?o ?m)))
     (:derived (communicated_image_data_UG ?o - objective ?m - mode) (and (not (communicated_image_data ?o ?m)) (communicated_image_data_G ?o ?m)))
     (:derived (communicated_rock_data_AG ?w - waypoint) (and (communicated_rock_data ?w) (communicated_rock_data_G ?w)))
     (:derived (communicated_rock_data_UG ?w - waypoint) (and (not (communicated_rock_data ?w)) (communicated_rock_data_G ?w)))
     (:derived (communicated_soil_data_AG ?w - waypoint) (and (communicated_soil_data ?w) (communicated_soil_data_G ?w)))
     (:derived (communicated_soil_data_UG ?w - waypoint) (and (not (communicated_soil_data ?w)) (communicated_soil_data_G ?w)))
     (:derived (derivable_calibrate) (exists (?t - objective ?i - camera ?r - rover ?w - waypoint) (and (equipped_for_imaging ?r) (calibration_target ?i ?t) (at ?r ?w) (visible_from ?t ?w) (on_board ?i ?r) (calibrate_ ?r ?i ?t ?w))))
     (:derived (derivable_calibrated_and_supports_mode ?M) (exists (?I ?R) (and (calibrated ?I ?R) (supports_mode ?R ?I ?M))))
     (:derived (derivable_communicate_image_data) (exists (?o - objective ?r - rover ?x - waypoint ?y - waypoint ?m - mode ?l - lander) (and (at ?r ?x) (at_lander ?l ?y) (have_image ?r ?o ?m) (visible ?x ?y) (communicate_image_data_ ?r ?l ?o ?m ?x ?y))))
     (:derived (derivable_communicate_rock_data) (exists (?r - rover ?x - waypoint ?y - waypoint ?p - waypoint ?l - lander) (and (at ?r ?x) (at_lander ?l ?y) (have_rock_analysis ?r ?p) (visible ?x ?y) (communicate_rock_data_ ?r ?l ?p ?x ?y))))
     (:derived (derivable_communicate_soil_data) (exists (?r - rover ?x - waypoint ?y - waypoint ?p - waypoint ?l - lander) (and (at ?r ?x) (at_lander ?l ?y) (have_soil_analysis ?r ?p) (visible ?x ?y) (communicate_soil_data_ ?r ?l ?p ?x ?y))))
     (:derived (derivable_drop) (exists (?y - store ?x - rover) (and (store_of ?y ?x) (full ?y))))
     (:derived (derivable_empty_rock) (exists (?S ?R) (and (empty ?S) (equipped_for_rock_analysis ?R) (store_of ?S ?R))))
     (:derived (derivable_empty_soil) (exists (?S ?R) (and (empty ?S) (equipped_for_soil_analysis ?R) (store_of ?S ?R))))
     (:derived (derivable_navigate) (exists (?y - waypoint ?r - rover ?x - waypoint) (and (not (at ?r ?y)) (at ?r ?x) (navigate_ ?r ?x ?y))))
     (:derived (derivable_sample_rock) (exists (?p - waypoint ?s - store ?x - rover) (and (at ?x ?p) (at_rock_sample ?p) (equipped_for_rock_analysis ?x) (store_of ?s ?x) (empty ?s) (sample_rock_ ?x ?s ?p))))
     (:derived (derivable_sample_soil) (exists (?p - waypoint ?s - store ?x - rover) (and (at ?x ?p) (at_soil_sample ?p) (equipped_for_soil_analysis ?x) (store_of ?s ?x) (empty ?s) (sample_soil_ ?x ?s ?p))))
     (:derived (derivable_take_image) (exists (?o - objective ?r - rover ?i - camera ?p - waypoint ?m - mode) (and (calibrated ?i ?r) (on_board ?i ?r) (equipped_for_imaging ?r) (supports ?i ?m) (visible_from ?o ?p) (at ?r ?p) (take_image_ ?r ?p ?o ?i ?m))))
     (:derived (derivable_uncollected_goal_image) (exists (?O ?M) (uncollected_goal_image ?O ?M)))
     (:derived (derivable_uncollected_goal_rock) (exists (?P) (uncollected_goal_rock ?P)))
     (:derived (derivable_uncollected_goal_soil) (exists (?P) (uncollected_goal_soil ?P)))
     (:derived (empty_AG ?s - store) (and (empty ?s) (empty_G ?s)))
     (:derived (empty_UG ?s - store) (and (not (empty ?s)) (empty_G ?s)))
     (:derived (equipped_for_imaging_AG ?r - rover) (and (equipped_for_imaging ?r) (equipped_for_imaging_G ?r)))
     (:derived (equipped_for_imaging_UG ?r - rover) (and (not (equipped_for_imaging ?r)) (equipped_for_imaging_G ?r)))
     (:derived (equipped_for_rock_analysis_AG ?r - rover) (and (equipped_for_rock_analysis ?r) (equipped_for_rock_analysis_G ?r)))
     (:derived (equipped_for_rock_analysis_UG ?r - rover) (and (not (equipped_for_rock_analysis ?r)) (equipped_for_rock_analysis_G ?r)))
     (:derived (equipped_for_soil_analysis_AG ?r - rover) (and (equipped_for_soil_analysis ?r) (equipped_for_soil_analysis_G ?r)))
     (:derived (equipped_for_soil_analysis_UG ?r - rover) (and (not (equipped_for_soil_analysis ?r)) (equipped_for_soil_analysis_G ?r)))
     (:derived (full_AG ?s - store) (and (full ?s) (full_G ?s)))
     (:derived (full_UG ?s - store) (and (not (full ?s)) (full_G ?s)))
     (:derived (have_image_AG ?r - rover ?o - objective ?m - mode) (and (have_image ?r ?o ?m) (have_image_G ?r ?o ?m)))
     (:derived (have_image_UG ?r - rover ?o - objective ?m - mode) (and (not (have_image ?r ?o ?m)) (have_image_G ?r ?o ?m)))
     (:derived (have_rock_analysis_AG ?r - rover ?w - waypoint) (and (have_rock_analysis ?r ?w) (have_rock_analysis_G ?r ?w)))
     (:derived (have_rock_analysis_UG ?r - rover ?w - waypoint) (and (not (have_rock_analysis ?r ?w)) (have_rock_analysis_G ?r ?w)))
     (:derived (have_soil_analysis_AG ?r - rover ?w - waypoint) (and (have_soil_analysis ?r ?w) (have_soil_analysis_G ?r ?w)))
     (:derived (have_soil_analysis_UG ?r - rover ?w - waypoint) (and (not (have_soil_analysis ?r ?w)) (have_soil_analysis_G ?r ?w)))
     (:derived (navigate_ ?R - rover ?X - waypoint ?Y - waypoint) (and (navigate_priority) (uncollected_goal_rock ?Y) (at_rock_sample ?Y) (equipped_for_rock_analysis ?R)))
     (:derived (navigate_ ?R - rover ?X - waypoint ?Y - waypoint) (and (navigate_priority) (uncollected_goal_soil ?Y) (at_soil_sample ?Y) (equipped_for_soil_analysis ?R)))
     (:derived (navigate_ ?R - rover ?X - waypoint ?Y - waypoint) (exists (?I ?O ?M) (and (navigate_priority) (uncollected_goal_image ?O ?M) (supports_mode ?R ?I ?M) (calibrated ?I ?R) (visible_from ?O ?Y))))
     (:derived (navigate_ ?R - rover ?X - waypoint ?Y - waypoint) (exists (?I ?T ?O ?M) (and (navigate_priority) (uncollected_goal_image ?O ?M) (supports_mode ?R ?I ?M) (calibration_target ?I ?T) (visible_from ?T ?Y) (not (derivable_calibrated_and_supports_mode ?M)))))
     (:derived (navigate_ ?R - rover ?X - waypoint ?Y - waypoint) (exists (?L ?O ?M ?Z) (and (navigate_priority) (communicated_image_data_UG ?O ?M) (have_image ?R ?O ?M) (at_lander ?L ?Z) (visible ?Y ?Z))))
     (:derived (navigate_ ?R - rover ?X - waypoint ?Y - waypoint) (exists (?P ?L ?Z) (and (navigate_priority) (communicated_rock_data_UG ?P) (have_rock_analysis ?R ?P) (at_lander ?L ?Z) (visible ?Y ?Z))))
     (:derived (navigate_ ?R - rover ?X - waypoint ?Y - waypoint) (exists (?P ?L ?Z) (and (navigate_priority) (communicated_soil_data_UG ?P) (have_soil_analysis ?R ?P) (at_lander ?L ?Z) (visible ?Y ?Z))))
     (:derived (navigate_priority) (and (not (derivable_sample_soil)) (not (derivable_sample_rock)) (not (derivable_drop)) (not (derivable_calibrate)) (not (derivable_take_image)) (not (derivable_communicate_soil_data)) (not (derivable_communicate_rock_data)) (not (derivable_communicate_image_data))))
     (:derived (on_board_AG ?i - camera ?r - rover) (and (on_board ?i ?r) (on_board_G ?i ?r)))
     (:derived (on_board_UG ?i - camera ?r - rover) (and (not (on_board ?i ?r)) (on_board_G ?i ?r)))
     (:derived (sample_rock_ ?R - rover ?S - store ?P - waypoint) (uncollected_goal_rock ?P))
     (:derived (sample_soil_ ?R - rover ?S - store ?P - waypoint) (uncollected_goal_soil ?P))
     (:derived (store_of_AG ?s - store ?r - rover) (and (store_of ?s ?r) (store_of_G ?s ?r)))
     (:derived (store_of_UG ?s - store ?r - rover) (and (not (store_of ?s ?r)) (store_of_G ?s ?r)))
     (:derived (supports_AG ?c - camera ?m - mode) (and (supports ?c ?m) (supports_G ?c ?m)))
     (:derived (supports_UG ?c - camera ?m - mode) (and (not (supports ?c ?m)) (supports_G ?c ?m)))
     (:derived (supports_mode ?R ?I ?M) (and (on_board ?I ?R) (equipped_for_imaging ?R) (supports ?I ?M)))
     (:derived (take_image_ ?R - rover ?P - waypoint ?O - objective ?I - camera ?M - mode) (uncollected_goal_image ?O ?M))
     (:derived (uncollected_goal_image ?O ?M) (and (communicated_image_data_UG ?O ?M) (not (collected_image ?O ?M))))
     (:derived (uncollected_goal_rock ?P) (and (communicated_rock_data_UG ?P) (not (collected_rock ?P))))
     (:derived (uncollected_goal_soil ?P) (and (communicated_soil_data_UG ?P) (not (collected_soil ?P))))
     (:derived (visible_AG ?w - waypoint ?p - waypoint) (and (visible ?w ?p) (visible_G ?w ?p)))
     (:derived (visible_UG ?w - waypoint ?p - waypoint) (and (not (visible ?w ?p)) (visible_G ?w ?p)))
     (:derived (visible_from_AG ?o - objective ?w - waypoint) (and (visible_from ?o ?w) (visible_from_G ?o ?w)))
     (:derived (visible_from_UG ?o - objective ?w - waypoint) (and (not (visible_from ?o ?w)) (visible_from_G ?o ?w)))
    (:action calibrate
        :parameters (?r - rover ?i - camera ?t - objective ?w - waypoint)
        :precondition (and (equipped_for_imaging ?r) (calibration_target ?i ?t) (at ?r ?w) (visible_from ?t ?w) (on_board ?i ?r) (calibrate_ ?r ?i ?t ?w))
        :effect (calibrated ?i ?r)
    )
     (:action communicate_image_data
        :parameters (?r - rover ?l - lander ?o - objective ?m - mode ?x - waypoint ?y - waypoint)
        :precondition (and (at ?r ?x) (at_lander ?l ?y) (have_image ?r ?o ?m) (visible ?x ?y) (communicate_image_data_ ?r ?l ?o ?m ?x ?y))
        :effect (communicated_image_data ?o ?m)
    )
     (:action communicate_rock_data
        :parameters (?r - rover ?l - lander ?p - waypoint ?x - waypoint ?y - waypoint)
        :precondition (and (at ?r ?x) (at_lander ?l ?y) (have_rock_analysis ?r ?p) (visible ?x ?y) (communicate_rock_data_ ?r ?l ?p ?x ?y))
        :effect (communicated_rock_data ?p)
    )
     (:action communicate_soil_data
        :parameters (?r - rover ?l - lander ?p - waypoint ?x - waypoint ?y - waypoint)
        :precondition (and (at ?r ?x) (at_lander ?l ?y) (have_soil_analysis ?r ?p) (visible ?x ?y) (communicate_soil_data_ ?r ?l ?p ?x ?y))
        :effect (communicated_soil_data ?p)
    )
     (:action drop
        :parameters (?x - rover ?y - store)
        :precondition (and (store_of ?y ?x) (full ?y))
        :effect (and (not (full ?y)) (empty ?y))
    )
     (:action navigate
        :parameters (?r - rover ?x - waypoint ?y - waypoint)
        :precondition (and (not (at ?r ?y)) (at ?r ?x) (navigate_ ?r ?x ?y))
        :effect (and (not (at ?r ?x)) (at ?r ?y))
    )
     (:action sample_rock
        :parameters (?x - rover ?s - store ?p - waypoint)
        :precondition (and (at ?x ?p) (at_rock_sample ?p) (equipped_for_rock_analysis ?x) (store_of ?s ?x) (empty ?s) (sample_rock_ ?x ?s ?p))
        :effect (and (not (empty ?s)) (full ?s) (have_rock_analysis ?x ?p) (not (at_rock_sample ?p)))
    )
     (:action sample_soil
        :parameters (?x - rover ?s - store ?p - waypoint)
        :precondition (and (at ?x ?p) (at_soil_sample ?p) (equipped_for_soil_analysis ?x) (store_of ?s ?x) (empty ?s) (sample_soil_ ?x ?s ?p))
        :effect (and (not (empty ?s)) (full ?s) (have_soil_analysis ?x ?p) (not (at_soil_sample ?p)))
    )
     (:action take_image
        :parameters (?r - rover ?p - waypoint ?o - objective ?i - camera ?m - mode)
        :precondition (and (calibrated ?i ?r) (on_board ?i ?r) (equipped_for_imaging ?r) (supports ?i ?m) (visible_from ?o ?p) (at ?r ?p) (take_image_ ?r ?p ?o ?i ?m))
        :effect (and (have_image ?r ?o ?m) (not (calibrated ?i ?r)))
    )
)