(define (problem rover-01)
    (:domain rover)
    (:requirements :derived-predicates :existential-preconditions :negative-preconditions :strips :typing)
    (:objects camera1 - camera general - lander colour high_res low_res - mode objective1 - objective rover1 - rover rover1store - store waypoint1 waypoint2 - waypoint)
    (:init (at rover1 waypoint1) (at_lander general waypoint1) (calibration_target camera1 objective1) (communicated_image_data_G objective1 colour) (communicated_image_data_G objective1 high_res) (communicated_image_data_G objective1 low_res) (empty rover1store) (equipped_for_imaging rover1) (equipped_for_rock_analysis rover1) (equipped_for_soil_analysis rover1) (on_board camera1 rover1) (store_of rover1store rover1) (supports camera1 colour) (supports camera1 high_res) (supports camera1 low_res) (visible waypoint1 waypoint2) (visible waypoint2 waypoint1) (visible_from objective1 waypoint2))
    (:goal (and (communicated_image_data objective1 high_res) (communicated_image_data objective1 low_res) (communicated_image_data objective1 colour)))
)